### PR TITLE
Ui/page history

### PR DESCRIPTION
**Pull request by craxrev**
Integrate the history page new design

### CODE REVIEW

**Review by haythemsellami — COMMENTED** [review]
cool, the ColorHash thing can be put in a provider as it is used in many pages... but we can refactor that later

**Comment by haythemsellami** [comment]
I'll just move the pipe somewhere else and inject it in the app module...

**Comment by craxrev** [comment]
> cool, the ColorHash thing can be put in a provider as it is used in many pages... but we can refactor that later

yes ofc

> I'll just move the pipe somewhere else and inject it in the app module...

I thought I'll find a folder like `shared` where I can put shared components, directives, pipes.. 
you may as well do that, we may even need it in the future

**Comment by haythemsellami** [comment]
> I thought I'll find a folder like `shared` where I can put shared components, directives, pipes..
> you may as well do that, we may even need it in the future

for ionic the providers are in the `providers` directory and pipe in `pipe` directory.
BTW you can generate them using `ionic generate` command.

**Pull request merged**
